### ISSUE TITLE
Add Programming-Books

### ISSUE THREAD

**Issue by dev-aniketj** [pawelborkar/awesome-repos#8]
**What's your entry is about?**

**For which entry you want to create a new category?**

**Additional context**

Link - https://github.com/dev-aniketj/Programming-Books

**Comment by pawelborkar** [comment]
Hi @dev-aniketj,
You can add this repo into the [Books](https://github.com/pawelborkar/awesome-repos#books) category.
Can you please raise the PR for the same? Don't forget to read the [contribution guide](https://github.com/pawelborkar/awesome-repos/blob/master/CONTRIBUTING.md)
Thanks.
